name: Java CI with Gradle
'on':
  push:
    branches:
      - master
jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build with Gradle
        run: gradle test

  sonarqube:
    runs-on: ubuntu-latest
    needs: unittest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Sonarqube analyze
        run: gradle build && gradle sonarqube -Dsonar.projectKey=${{ secrets.SONARQUBE_PROJECT_KEY }} -Dsonar.host.url=${{ secrets.SONARQUBE_HOST }} -Dsonar.login=${{ secrets.SONARQUBE_TOKEN }}

  deploy:
    runs-on: ubuntu-latest
    name: Deploy the JAR file to the remote server
    needs: sonarqube
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Generate the package using gradle
        run: gradle build
      - name: Deploy to remote server
        uses: garygrossgarten/github-action-scp@release
        with:
          local: build/libs/spring-boot-0.0.1-SNAPSHOT.jar
          remote: /home/ubuntu/spring-boot-0.0.1-SNAPSHOT.jar
          host: '${{ secrets.HOST }}'
          username: '${{ secrets.SSH_USER }}'
          privateKey: '${{ secrets.PRIVATE_KEY }}'
      - name: Run script on remote server
        if: always()
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd /home/ubuntu && java -jar spring-boot-0.0.1-SNAPSHOT.jar &
          host: '${{ secrets.HOST }}'
          user: '${{ secrets.SSH_USER }}'
          key: '${{ secrets.PRIVATE_KEY }}'
          args: '-tt'
